print('---DESAFIO 09---')
n=int(input('Digite aqui um número para ver a sua tabuada:'))
m=(n*1)
o=(n*2)
p=(n*3)
q=(n*4)
r=(n*5)
s=(n*6)
t=(n*7)
u=(n*8)
v=(n*9)
w=(n*10)
print('-' * 12)
print('{} * 1 = {}'.format(n,m))
print('{} * 2 = {}'.format(n,o))
print('{} * 3 = {}'.format(n,p))
print('{} * 4 = {}'.format(n,q))
print('{} * 5 = {}'.format(n,r))
print('{} * 6 = {}'.format(n,s))
print('{} * 7 = {}'.format(n,t))
print('{} * 8 = {}'.format(n,u))
print('{} * 9 = {}'.format(n,v))
print('{} * 10 = {}'.format(n,w))
print('-' * 12)

